server:
  port: 8100

spring:
  application:
    name: ms-recargas
 HEAD

  rabbitmq:
    host: 192.168.18.91
    port: 5672
 0e87ccc15336a0aab705c93235319cb40681e889

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      ms-cuentas:
        slidingWindowSize: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 30s
 HEAD
        permittedNumberOfCallsInHalfOpenState: 1

        permittedNumberOfCallsInHalfOpenState: 1
 0e87ccc15336a0aab705c93235319cb40681e889
